<a href="https://colab.research.google.com/github/TanmayJainModi/ML_algorithms/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementation of Logistic Rergression from scratch

In [ ]:
import pandas as pd
df = pd.read_csv('processed_cleveland.csv',na_values='?')
df.dropna(inplace=True)
#Gave an unicodedecode error stating that pandas couldn't decode the .data file
#using the default encoding utf-8
print(df.head())

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3
1   67    1   4       160   286    0        2      108      1      1.5      2
2   67    1   4       120   229    0        2      129      1      2.6      2
3   37    1   3       130   250    0        0      187      0      3.5      3
4   41    0   2       130   204    0        2      172      0      1.4      1

    ca  thal  num
0  0.0   6.0    0
1  3.0   3.0    2
2  2.0   7.0    1
3  0.0   3.0    0
4  0.0   3.0    0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 297 entries, 0 to 301
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       297 non-null    int64
 1   sex       297 non-null    int64
 2   cp        297 non-null    int64
 3   trestbps  297 non-null    int64
 4   chol      297 non-null    int64
 5   fbs       297 non-null    int64
 6   restecg   297 non-null    int64
 7   thalach   297 non-null    int64
 8   exang     297 non-null    int64
 9   oldpeak   297 non-null    float64
 10  slope     297 non-null    int64
 11  ca        297 non-null    float64
 12  thal      297 non-null    float64
 13  num       297 non-null    int64
dtypes: float64(3), int64(11)
memory usage: 34.8 KB

In [ ]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [ ]:
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
import numpy as np


X = df.drop('num', axis=1)
y = df['num']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""X, y = make_classification(n_samples=303,  # Number of samples (same as Cleveland dataset size)
                           n_features=13,  # 13 features as in Cleveland dataset
                           n_informative=10,  # 10 informative features
                           n_redundant=0,  # No redundant features
                           n_classes=2,  # Binary classification (heart disease vs no heart disease)
                           random_state=42)  # Ensures reproducibility"""

'X, y = make_classification(n_samples=303,  # Number of samples (same as Cleveland dataset size)\n                           n_features=13,  # 13 features as in Cleveland dataset\n                           n_informative=10,  # 10 informative features\n                           n_redundant=0,  # No redundant features\n                           n_classes=2,  # Binary classification (heart disease vs no heart disease)\n                           random_state=42)  # Ensures reproducibility'

In [ ]:
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57,0,4,140,241,0,0,123,1,0.2,2,0.0,7.0
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0

In [ ]:
X_scaled.shape

(297, 13)

SPLITTING THE DATA

In [ ]:
y.shape

(297,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X_scaled , y , test_size=0.2 , random_state=42)

In [ ]:
X_train

array([[-1.72030648, -1.44697961, -0.16428947, ...,  0.6437811 ,
        -0.72197605, -0.89422007],
       [ 0.60411976, -1.44697961, -2.24062879, ..., -0.97658319,
        -0.72197605, -0.89422007],
       [ 1.60030243, -1.44697961, -2.24062879, ..., -0.97658319,
         1.41162482, -0.89422007],
       ...,
       [ 0.27205887,  0.69109474, -0.16428947, ...,  0.6437811 ,
         0.34482438,  1.17257652],
       [ 0.49343279,  0.69109474, -2.24062879, ..., -0.97658319,
         1.41162482, -0.89422007],
       [ 1.82167636, -1.44697961, -0.16428947, ..., -0.97658319,
         0.34482438, -0.89422007]])

In [ ]:
"""class Logistic_Regression:

  #declaring teh hyperparameters -> learning rate and number of iterations(also called epoch)
  def __init__(self, learning_rate, no_of_iterations):
    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations


  # fitting the model
  def fit(self, X, Y):
    #no of datapoints(rows) in the dataset -->m
    #no of features(columns) in the dataset -->n
    self.m , self.n = X.shape

    #initializing weight and bias values
    self.w = np.ones(self.n)
    self.b = 1
    self.X = X
    self.Y = Y

    #gradient descent
    for i in range(self.no_of_iterations):
      self.update_weights()


  def update_weights(self):

    #y_hat formula (sigmoid function)
    Y_hat = 1/(1 + np.exp(- (self.X.dot(self.w) + self.b)))

    #derivatives
    dw = (1/self.m)*np.dot(self.X.T, (Y_hat - self.Y))
    db = (1/self.m)*np.sum(Y_hat - self.Y)


    #update the weights and bias using gradient descent
    self.w = self.w - self.learning_rate * dw
    self.b = self.b - self.learning_rate * db

  # Sigmoid equation and decision boundary
  def predict(self,X):
    Y_pred = 1 / (1 + np.exp( - (X.dot(self.w) + self.b ) ))
    Y_pred = np.where( Y_pred > 0.5, 1, 0)
    return Y_pred"""

In [ ]:
class Logistic_Regression:

  #declaring teh hyperparameters -> learning rate and number of iterations(also called epoch)
  def __init__(self, learning_rate, no_of_iterations):
    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations


  # fitting the model
  def fit(self, X, Y):
    #initializing weight and bias values

    self.X = X
    self.X = np.insert(self.X, 0, 1, axis=1)
    self.w = np.ones(self.X.shape[1])
    self.Y = Y

    #no of datapoints(rows) in the dataset -->m
    #no of features(columns) in the dataset -->n
    self.m , self.n = self.X.shape

    #gradient descent
    for i in range(self.no_of_iterations):
      self.update_weights()


  def update_weights(self):

    #y_hat formula (sigmoid function)
    Y_hat = 1/(1 + np.exp(- (self.X.dot(self.w))))

    #derivatives
    dw = (1/self.m)*np.dot(self.X.T, (self.Y - Y_hat))
    #db = (1/self.m)*np.sum(Y_hat - self.Y)


    #update the weights and bias using gradient descent
    self.w = self.w + self.learning_rate * dw
    #self.b = self.b - self.learning_rate * db

  # Sigmoid equation and decision boundary
  def predict(self,x):
    self.x = x
    self.x = np.insert(self.x, 0, 1, axis=1)
    Y_pred = 1 / (1 + np.exp( - (self.x.dot(self.w)) ))
    Y_pred = np.where( Y_pred > 0.5, 1, 0)
    return Y_pred

In [ ]:
lr = Logistic_Regression(learning_rate=0.01, no_of_iterations=100000)
lr.fit(X_train, y_train)

In [ ]:
lr.w

array([-0.05813308, -0.09954639,  0.704792  ,  0.37369513,  0.50783281,
        0.35917055, -0.47337018,  0.21066612, -0.49922684,  0.44371468,
        0.34051183,  0.27077818,  1.23004558,  0.53475695])

In [ ]:
X.shape

(297, 13)

In [ ]:
from sklearn.metrics import accuracy_score
y_pred_training = lr.predict(X_train)
training_data_accracy = accuracy_score(y_train, y_pred_training)
print(training_data_accracy)

0.8438818565400844

In [ ]:
y_pred_testing = lr.predict(X_test)
testing_data_accracy = accuracy_score(y_test, y_pred_testing)
print(testing_data_accracy)

0.8666666666666667

In [ ]:
y_pred_training

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [ ]:
y_train

277    0
262    0
30     0
22     1
281    0
      ..
190    0
71     1
107    1
274    1
103    0
Name: num, Length: 237, dtype: int64

In [ ]:
lr.w.shape

(14,)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

In [ ]:
print(f"Precision: {precision_score(y_test, y_pred_testing):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_testing):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_testing):.4f}")
print(f"ROC AUC: {roc_auc_score(y_test, y_pred_testing):.4f}")

Precision: 0.8333
Recall: 0.8333
F1-Score: 0.8333
ROC AUC: 0.8611